config/routes.rb
Rails.application.routes.draw do
  resources :sales
  resources :products
  devise_for :users

  root to: 'home#index'  
  resources :activities

end

app/models/ability.rb
class Ability  
  include CanCan::Ability  
  def initialize(user)  
   if user.present?  
    if user.role.name == 'admin'  
     can :manage, :all  
    else  
     can :create , Product  
     can :create , Sale  
     can :read, :all  
    end  
   else  
    can :read, :all  
   end  
  end  
 end

app/models/item.rb
class Item < ActiveRecord::Base
    before_save :set_total  
  def set_total  
   if self.quantity.blank?  
    0  
   else  
        self.total = self.quantity * self.product.price  
   end  
  end  
  def subtotal  
   if self.quantity.blank?  
    0  
   else  
        self.quantity * self.product.price  
   end  
  end 

  belongs_to :product
  belongs_to :sale
end

app/models/product.rb
class Product < ActiveRecord::Base
  before_create :set_code  
  def generate_code(size = 6)  
   charset = %w{ 2 3 4 6 7 9 A C D E F G H J K M N P Q R T V W X Y Z}  
   (0...size).map{ charset.to_a[rand(charset.size)] }.join  
  end  
  def set_code  
   self.code = generate_code(6)  
  end 

  include PublicActivity::Model  
  tracked owner: ->(controller, model) { controller && controller.current_user}


  belongs_to :user
  has_many :items
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users
end

app/models/sale.rb
class Sale < ActiveRecord::Base
   def subtotals  
   self.items.map { |i| i.subtotal }  
  end  
  def total_all  
   subtotals.sum  
  end 

  include PublicActivity::Model  
  tracked owner: ->(controller, model) { controller && controller.current_user}
  
  belongs_to :user
  has_many :items
  accepts_nested_attributes_for :items, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :set_default_role

  private  
  def set_default_role  
   self.role ||= Role.find_by_name('user')  
  end  

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :role
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index  
   @activities = PublicActivity::Activity.all
 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	 include PublicActivity::StoreController  

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
 rescue_from CanCan::AccessDenied do |exception|  
   flash[:error] = "Access denied."  
   redirect_to root_url  
  end

  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController  
  before_action :set_product, only: [:show, :edit, :update, :destroy]  
  load_and_authorize_resource  
  # GET /products  
  # GET /products.json  
  def index  
   @products = Product.all  
  end  
  # GET /products/1  
  # GET /products/1.json  
  def show  
  end  
  # GET /products/new  
  def new  
   @product = Product.new  
  end  
  # GET /products/1/edit  
  def edit  
  end  
  # POST /products  
  # POST /products.json  
  def create  
   @product = Product.new(product_params)  
   @product.user_id = current_user.id #tambahkan code ini setelah code diatas   
   respond_to do |format|  
    if @product.save  
     format.html { redirect_to @product, notice: 'Product was successfully created.' }  
     format.json { render :show, status: :created, location: @product }  
    else  
     format.html { render :new }  
     format.json { render json: @product.errors, status: :unprocessable_entity }  
    end  
   end  
  end  
  # PATCH/PUT /products/1  
  # PATCH/PUT /products/1.json  
  def update  
   respond_to do |format|  
    if @product.update(product_params)  
     format.html { redirect_to @product, notice: 'Product was successfully updated.' }  
     format.json { render :show, status: :ok, location: @product }  
    else  
     format.html { render :edit }  
     format.json { render json: @product.errors, status: :unprocessable_entity }  
    end  
   end  
  end  
  # DELETE /products/1  
  # DELETE /products/1.json  
  def destroy  
   @product.destroy  
   respond_to do |format|  
    format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }  
    format.json { head :no_content }  
   end  
  end  
  private  
   # Use callbacks to share common setup or constraints between actions.  
   def set_product  
    @product = Product.find(params[:id])  
   end  
   # Never trust parameters from the scary internet, only allow the white list through.  
   def product_params  
    params.require(:product).permit(:code, :name, :price, :user_id)  
   end  
 end

app/controllers/sales_controller.rb
class SalesController < ApplicationController  
  before_action :set_sale, only: [:show, :edit, :update, :destroy]  
  load_and_authorize_resource  
  # GET /sales  
  # GET /sales.json  
  def index  
   @sales = Sale.all  
  end  
  # GET /sales/1  
  # GET /sales/1.json  
  def show  
  end  
  # GET /sales/new  
  def new  
   @sale = Sale.new  
  end  
  # GET /sales/1/edit  
  def edit  
  end  
  # POST /sales  
  # POST /sales.json  
  def create  
   @sale = Sale.new(sale_params)  
   @sale.user_id = current_user.id #tambahkan ini setelah code di atas   
   @sale.total = @sale.total_all #tambahkan ini setelah code di atas  
   respond_to do |format|  
    if @sale.save  
     format.html { redirect_to @sale, notice: 'Sale was successfully created.' }  
     format.json { render :show, status: :created, location: @sale }  
    else  
     format.html { render :new }  
     format.json { render json: @sale.errors, status: :unprocessable_entity }  
    end  
   end  
  end  
  # PATCH/PUT /sales/1  
  # PATCH/PUT /sales/1.json  
  def update  
   respond_to do |format|  
    if @sale.update(sale_params)  
     format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }  
     format.json { render :show, status: :ok, location: @sale }  
    else  
     format.html { render :edit }  
     format.json { render json: @sale.errors, status: :unprocessable_entity }  
    end  
   end  
  end  
  # DELETE /sales/1  
  # DELETE /sales/1.json  
  def destroy  
   @sale.destroy  
   respond_to do |format|  
    format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }  
    format.json { head :no_content }  
   end  
  end  
  private  
   # Use callbacks to share common setup or constraints between actions.  
   def set_sale  
    @sale = Sale.find(params[:id])  
   end  
   # Never trust parameters from the scary internet, only allow the white list through.  
   def sale_params  
    params.require(:sale).permit(:name, items_attributes: [:id,:product_id, :price,:quantity,:total,:_destroy])  
   end  
 end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	

	def link_to_add_fields(name, f, association)  
   new_object = f.object.send(association).klass.new  
   id = new_object.object_id  
   fields = f.fields_for(association, new_object, child_index: id) do |builder|  
    render(association.to_s.singularize + "_fields", f: builder)  
   end  
   link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})  
  end




	def flash_class(type)
		case type
		when :alert
			"alert-danger"
		when :notice
			"alert-success"
		else
			"" end
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/activities/index.html.erb
 <h1>Listing Activities</h1>  
 <table class="table table-striped table-bordered table-condensed sortable">  
   <thead>  
     <tr>  
       <th><%= "Activities"%></th>  
     </tr>  
   </thead>  
   <tbody>  
        <% @activities.each do |activity| %>  
     <tr>  
       <td valign="top">   
         <%= activity.owner.email %>  
         <%= render_activity activity %>  
       </td>  
     </tr>  
     <% end %>  
   </tbody>  
   <tfoot>  
     <tr>  
       <td colspan="3"></td>  
     </tr>  
   </tfoot>  
 </table>

app/views/activity/product/_create.html.erb
 added product  
 <% if activity.trackable %>  
  <%= link_to activity.trackable.name, product_path(activity.trackable.id) %>  
 <% else %>  
  which has since been removed  
 <% end %> 

app/views/activity/product/_destroy.html.erb
 removed a produc  

app/views/activity/product/_update.html.erb
 Updated product  
 <% if activity.trackable %>  
  <%= link_to activity.trackable.name, product_path(activity.trackable.id) %>  
 <% else %>  
  which has since been removed  
 <% end %>

app/views/activity/sale/_create.html.erb
 added product  
 <% if activity.trackable %>  
  <%= link_to activity.trackable.name, product_path(activity.trackable.id) %>  
 <% else %>  
  which has since been removed  
 <% end %>

app/views/activity/sale/_destroy.html.erb
 removed a produc  

app/views/activity/sale/_update.html.erb
 Updated product  
 <% if activity.trackable %>  
  <%= link_to activity.trackable.name, product_path(activity.trackable.id) %>  
 <% else %>  
  which has since been removed  
 <% end %>

app/views/home/index.html.erb
<p>welcome</p>

app/views/layouts/application.html.erb
  <!DOCTYPE html>   
  <html>   
  <head>   
    <title>Sale</title>   
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>   
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>   
    <%= csrf_meta_tags %>   
  </head>   
  <body>   
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">   
       <div class="container">   
         <div class="navbar-header">   
            <a class="navbar-brand" href="#">Sale</a>   
         </div>   
         <ul class="nav navbar-nav">
         <li><%= link_to "All Sales", sales_path %></li>  
         <li><%= link_to "All Products", products_path %></li>      
         <li><%= link_to "All Activities", activities_path %></li>
         </ul>   
         <ul class="nav navbar-nav navbar-right">   
            <% if user_signed_in? %>   
            <li><%= link_to current_user.email, edit_user_registration_path %></li>   
            <li><%= link_to "Log Out" , destroy_user_session_path, method: :delete %></li>   
            <% else %>   
            <li><%= link_to "Sign In", user_session_path %></li>   
            <li><%= link_to "Register", new_user_registration_path %></li>   
            <% end %>   
         </ul>   
       </div>   
    </div>   
    <div class="container">   
       <% flash.each do |type, message| %>   
       <div class="alert <%= flash_class type %> alert-dismissable">   
         <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>   
         <p><%= message %></p>   
       </div>   
       <% end %>   
       <%= yield %>   
    </div>   
  </body>   
  </html>   

app/views/products/_form.html.erb
 <%= form_for(@product) do |f| %>  
  <% if @product.errors.any? %>  
   <div id="error_explanation">  
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>  
    <ul>  
    <% @product.errors.full_messages.each do |message| %>  
     <li><%= message %></li>  
    <% end %>  
    </ul>  
   </div>  
  <% end %>  
  <div class="field">  
   <%= f.label :name %><br>  
   <%= f.text_field :name %>  
  </div>  
  <div class="field">  
   <%= f.label :price %><br>  
   <%= f.text_field :price %>  
  </div>  
  <div class="actions">  
   <%= f.submit %>  
  </div>  
 <% end %>  

app/views/products/_item_fields.html.erb
 <fieldset>  
  <%= f.label :product, "Product" %>  
  <%= f.collection_select :product_id, Product.all, :id, :name %>  
  <%= f.label :quantity, "Quantity" %>  
  <%= f.text_field :quantity, class: 'padli' %>  
  <%= f.hidden_field :_destroy %>  
  <%= link_to "remove", '#', class: "remove_fields" %>  
 </fieldset>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
 <h1>Listing Product</h1>  
 <table class="table table-striped">  
  <thead>  
   <tr>  
    <th>Name</th>  
    <th>Code</th>  
    <th>Price</th>  
    <th></th>  
    <th colspan="3"></th>  
   </tr>  
  </thead>  
  <tbody>  
   <% @products.each do |product| %>  
    <tr>  
     <td><%= product.name %></td>  
     <td><%= product.code %></td>  
     <td><%= product.price %></td>  
     <td><%= link_to 'Show', product %></td>
     <% if can? :update, Sale %>  
     <td><%= link_to 'Edit', edit_product_path(product) %></td>
     <% end %>  
     <td>  
       <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>  
     </td>  
    </tr>  
   <% end %>  
  </tbody>  
 </table>  
 <br>  
 <%= link_to 'New Product', new_product_path %>  

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @product.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>User:</strong>
  <%= @product.user %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>  
  <% if @sale.errors.any? %>  
   <div id="error_explanation">  
    <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>  
    <ul>  
    <% @sale.errors.full_messages.each do |message| %>  
     <li><%= message %></li>  
    <% end %>  
    </ul>  
   </div>  
  <% end %>  
  <div class="field">  
   <%= f.label :name %><br>  
   <%= f.text_field :name %>  
  </div>  
  <%= f.fields_for :items do |builder| %>   
    <%= render 'item_fields', f: builder %>   
  <% end %>   
  <%= link_to_add_fields "Add Item", f, :items %>   
  <div class="actions">  
   <%= f.submit %>  
  </div>  
 <% end %>  
 <script type="text/javascript">   
  jQuery(function() {   
   $('form').on('click', '.remove_fields', function(event) {   
   $(this).prev('input[type=hidden]').val('1');   
   $(this).closest('fieldset').hide();   
   return event.preventDefault();   
   });   
   return $('form').on('click', '.add_fields', function(event) {   
   var regexp, time;   
   time = new Date().getTime();   
   regexp = new RegExp($(this).data('id'), 'g');   
   $(this).before($(this).data('fields').replace(regexp, time));   
   return event.preventDefault();   
   });   
  });   
  </script>   

app/views/sales/_item_fields.html.erb
 <fieldset>  
  <%= f.label :product, "Product" %>  
  <%= f.collection_select :product_id, Product.all, :id, :name %>  
  <%= f.label :quantity, "Quantity" %>  
  <%= f.text_field :quantity, class: 'padli' %>  
  <%= f.hidden_field :_destroy %>  
  <%= link_to "remove", '#', class: "remove_fields" %>  
 </fieldset>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sales</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.name %></td>
        <td><%= sale.total %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>  
 <p>  
  <strong>Name:</strong>  
  <%= @sale.name %>  
 </p>  
 <%= link_to 'Edit', edit_sale_path(@sale) %> |  
 <%= link_to 'Back', sales_path %>  
 <h1>Listing Item</h1>  
 <table class="table table-striped">  
  <thead>  
   <tr>  
    <th>Product</th>  
    <th>price</th>  
    <th>quantity</th>  
    <th>total</th>  
    <th></th>  
   </tr>  
  </thead>  
  <tbody>  
   <% @sale.items.each do |item| %>  
    <tr>  
     <td><%= item.product.name %></td>  
     <td><%= item.product.price %></td>  
     <td><%= item.quantity %></td>  
     <td><%= item.total %></td>  
    </tr>  
   <% end %>  
  </tbody>  
 </table>  
 <hr>  
  <p> Total </p>  
  <%= @sale.total%>  
 <hr>